POST http://localhost:4001/tarefas
content-type: application/json

{
    "titulo": "SangatiBerga",
    "descricao": "DTD",
    "Date": "29/10/2024" 
}

###
GET http://localhost:4001/tarefas

###
GET http://localhost:4001/tarefas/3aed18e5-f7b7-4a6d-806f-636426989c73

###
PUT  http://localhost:4001/tarefas/3ec3eee0-782c-4b2f-969e-e1179b5189e1
content-type: application/json

{
    "titulo": "Berga",
    "descricao": "DTD",
    "Date": "29/10/2024" 
}