POST http://localhost:4001/tarefas HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "titulo": "SangatiBerga",
    "descricao": "Desenvolvimento"
    
}

###
GET http://localhost:4001/tarefas

###
GET http://localhost:4001/tarefas/d2e4219b-a9e2-46a5-8dc6-b5e3a5cfa8dc

###
PUT  http://localhost:4001/tarefas/8a055b8d-3184-47bc-9c1d-a9e650d682b7
content-type: application/json

{
    "titulo": "SB_TESTE",
    "descricao": "Desenvolvimento 1"
}

###
DELETE http://localhost:4001/tarefas/082219b9-d016-4515-9681-5f669e82b25c